// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExperimentChange(arg1) {
  return window['go']['core']['App']['AnalyzeExperimentChange'](arg1);
}

export function ArchiveExperiment(arg1, arg2) {
  return window['go']['core']['App']['ArchiveExperiment'](arg1, arg2);
}

export function AttachRunningApp(arg1) {
  return window['go']['core']['App']['AttachRunningApp'](arg1);
}

export function BackupProject(arg1, arg2) {
  return window['go']['core']['App']['BackupProject'](arg1, arg2);
}

export function CancelAgentTask(arg1, arg2, arg3) {
  return window['go']['core']['App']['CancelAgentTask'](arg1, arg2, arg3);
}

export function CancelAgentTaskContext(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['CancelAgentTaskContext'](arg1, arg2, arg3, arg4);
}

export function CancelClose() {
  return window['go']['core']['App']['CancelClose']();
}

export function CaptureAppPreview(arg1) {
  return window['go']['core']['App']['CaptureAppPreview'](arg1);
}

export function CheckServerHealth(arg1) {
  return window['go']['core']['App']['CheckServerHealth'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['core']['App']['ChooseDirectory'](arg1);
}

export function ChooseProjectWorkspaceBackground(arg1, arg2) {
  return window['go']['core']['App']['ChooseProjectWorkspaceBackground'](arg1, arg2);
}

export function ChooseProjectWorkspacePhoto(arg1, arg2) {
  return window['go']['core']['App']['ChooseProjectWorkspacePhoto'](arg1, arg2);
}

export function CleanupProjectRuntime(arg1) {
  return window['go']['core']['App']['CleanupProjectRuntime'](arg1);
}

export function CleanupProjectServers(arg1) {
  return window['go']['core']['App']['CleanupProjectServers'](arg1);
}

export function ClearProjectWorkspaceBackground(arg1, arg2) {
  return window['go']['core']['App']['ClearProjectWorkspaceBackground'](arg1, arg2);
}

export function CloneRepository(arg1) {
  return window['go']['core']['App']['CloneRepository'](arg1);
}

export function CompareExperiment(arg1) {
  return window['go']['core']['App']['CompareExperiment'](arg1);
}

export function ConfigureApp(arg1, arg2) {
  return window['go']['core']['App']['ConfigureApp'](arg1, arg2);
}

export function ConfigureAppContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['ConfigureAppContext'](arg1, arg2, arg3);
}

export function ConfirmClose() {
  return window['go']['core']['App']['ConfirmClose']();
}

export function ContinueExperimentChangeOnPrincipal(arg1, arg2) {
  return window['go']['core']['App']['ContinueExperimentChangeOnPrincipal'](arg1, arg2);
}

export function ControlSpotifyPlayback(arg1) {
  return window['go']['core']['App']['ControlSpotifyPlayback'](arg1);
}

export function CreateApp(arg1) {
  return window['go']['core']['App']['CreateApp'](arg1);
}

export function CreateExperiment(arg1) {
  return window['go']['core']['App']['CreateExperiment'](arg1);
}

export function CreateExperimentCheckpoint(arg1) {
  return window['go']['core']['App']['CreateExperimentCheckpoint'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['core']['App']['CreateProject'](arg1);
}

export function CreateServerDraft(arg1) {
  return window['go']['core']['App']['CreateServerDraft'](arg1);
}

export function DeleteApp(arg1) {
  return window['go']['core']['App']['DeleteApp'](arg1);
}

export function DeleteProject(arg1, arg2) {
  return window['go']['core']['App']['DeleteProject'](arg1, arg2);
}

export function DeleteProjectWorkspacePhoto(arg1, arg2, arg3) {
  return window['go']['core']['App']['DeleteProjectWorkspacePhoto'](arg1, arg2, arg3);
}

export function DeleteServer(arg1) {
  return window['go']['core']['App']['DeleteServer'](arg1);
}

export function DestroyServer(arg1) {
  return window['go']['core']['App']['DestroyServer'](arg1);
}

export function DetectDuplicateGroups(arg1) {
  return window['go']['core']['App']['DetectDuplicateGroups'](arg1);
}

export function DetectTerminalApp(arg1) {
  return window['go']['core']['App']['DetectTerminalApp'](arg1);
}

export function DiscardExperiment(arg1) {
  return window['go']['core']['App']['DiscardExperiment'](arg1);
}

export function DiscoverApps(arg1) {
  return window['go']['core']['App']['DiscoverApps'](arg1);
}

export function ExportProject(arg1, arg2) {
  return window['go']['core']['App']['ExportProject'](arg1, arg2);
}

export function ExportServerReproducibleConfig(arg1, arg2, arg3) {
  return window['go']['core']['App']['ExportServerReproducibleConfig'](arg1, arg2, arg3);
}

export function FocusApp(arg1) {
  return window['go']['core']['App']['FocusApp'](arg1);
}

export function GetAgentResourceSettings() {
  return window['go']['core']['App']['GetAgentResourceSettings']();
}

export function GetAppConsoleErrors(arg1) {
  return window['go']['core']['App']['GetAppConsoleErrors'](arg1);
}

export function GetAppLogs(arg1) {
  return window['go']['core']['App']['GetAppLogs'](arg1);
}

export function GetAppLogsContext(arg1, arg2) {
  return window['go']['core']['App']['GetAppLogsContext'](arg1, arg2);
}

export function GetAppStatus(arg1) {
  return window['go']['core']['App']['GetAppStatus'](arg1);
}

export function GetAppStatusContext(arg1, arg2) {
  return window['go']['core']['App']['GetAppStatusContext'](arg1, arg2);
}

export function GetAppearance() {
  return window['go']['core']['App']['GetAppearance']();
}

export function GetBrowserAutomationStatus(arg1) {
  return window['go']['core']['App']['GetBrowserAutomationStatus'](arg1);
}

export function GetEditorIntegrations() {
  return window['go']['core']['App']['GetEditorIntegrations']();
}

export function GetProjectContext(arg1) {
  return window['go']['core']['App']['GetProjectContext'](arg1);
}

export function GetProjectRoot() {
  return window['go']['core']['App']['GetProjectRoot']();
}

export function GetProjectThumbnail(arg1, arg2) {
  return window['go']['core']['App']['GetProjectThumbnail'](arg1, arg2);
}

export function GetProjectWorkspace(arg1, arg2) {
  return window['go']['core']['App']['GetProjectWorkspace'](arg1, arg2);
}

export function GetProjectWorkspaceBackground(arg1, arg2) {
  return window['go']['core']['App']['GetProjectWorkspaceBackground'](arg1, arg2);
}

export function GetProjectWorkspaceContext(arg1, arg2) {
  return window['go']['core']['App']['GetProjectWorkspaceContext'](arg1, arg2);
}

export function GetProjectWorkspacePhoto(arg1, arg2, arg3) {
  return window['go']['core']['App']['GetProjectWorkspacePhoto'](arg1, arg2, arg3);
}

export function GetServerLogs(arg1) {
  return window['go']['core']['App']['GetServerLogs'](arg1);
}

export function GetServerStats(arg1) {
  return window['go']['core']['App']['GetServerStats'](arg1);
}

export function GetSpotifyPlayback() {
  return window['go']['core']['App']['GetSpotifyPlayback']();
}

export function GetSpotifyPlaybackSince(arg1) {
  return window['go']['core']['App']['GetSpotifyPlaybackSince'](arg1);
}

export function GetWSLDistributions() {
  return window['go']['core']['App']['GetWSLDistributions']();
}

export function GroupDuplicate(arg1) {
  return window['go']['core']['App']['GroupDuplicate'](arg1);
}

export function ImportProjects(arg1) {
  return window['go']['core']['App']['ImportProjects'](arg1);
}

export function Initialize() {
  return window['go']['core']['App']['Initialize']();
}

export function InstallEditorIntegration(arg1) {
  return window['go']['core']['App']['InstallEditorIntegration'](arg1);
}

export function InstallWSLDistribution(arg1) {
  return window['go']['core']['App']['InstallWSLDistribution'](arg1);
}

export function IntegrateExperiment(arg1, arg2, arg3) {
  return window['go']['core']['App']['IntegrateExperiment'](arg1, arg2, arg3);
}

export function LinkExperimentAgentSession(arg1, arg2) {
  return window['go']['core']['App']['LinkExperimentAgentSession'](arg1, arg2);
}

export function ListAllServers() {
  return window['go']['core']['App']['ListAllServers']();
}

export function ListApps(arg1) {
  return window['go']['core']['App']['ListApps'](arg1);
}

export function ListExperiments(arg1, arg2) {
  return window['go']['core']['App']['ListExperiments'](arg1, arg2);
}

export function ListPendingAgentApprovals(arg1) {
  return window['go']['core']['App']['ListPendingAgentApprovals'](arg1);
}

export function ListProjectAgentSessions(arg1, arg2) {
  return window['go']['core']['App']['ListProjectAgentSessions'](arg1, arg2);
}

export function ListProjectAgentSessionsContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['ListProjectAgentSessionsContext'](arg1, arg2, arg3);
}

export function ListProjectTerminalSessions(arg1, arg2) {
  return window['go']['core']['App']['ListProjectTerminalSessions'](arg1, arg2);
}

export function ListProjectTerminalSessionsContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['ListProjectTerminalSessionsContext'](arg1, arg2, arg3);
}

export function ListProjects(arg1, arg2) {
  return window['go']['core']['App']['ListProjects'](arg1, arg2);
}

export function ListServerConnections(arg1, arg2) {
  return window['go']['core']['App']['ListServerConnections'](arg1, arg2);
}

export function ListServerServices(arg1, arg2) {
  return window['go']['core']['App']['ListServerServices'](arg1, arg2);
}

export function ListServers(arg1) {
  return window['go']['core']['App']['ListServers'](arg1);
}

export function ListServersContext(arg1, arg2) {
  return window['go']['core']['App']['ListServersContext'](arg1, arg2);
}

export function MoveNativeEditor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['App']['MoveNativeEditor'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenProject(arg1) {
  return window['go']['core']['App']['OpenProject'](arg1);
}

export function OpenProjectInEditor(arg1, arg2) {
  return window['go']['core']['App']['OpenProjectInEditor'](arg1, arg2);
}

export function PrepareExperimentIntegration(arg1, arg2) {
  return window['go']['core']['App']['PrepareExperimentIntegration'](arg1, arg2);
}

export function PrepareRuntimeClose() {
  return window['go']['core']['App']['PrepareRuntimeClose']();
}

export function PrepareServerClose() {
  return window['go']['core']['App']['PrepareServerClose']();
}

export function RegisterServerConnection(arg1) {
  return window['go']['core']['App']['RegisterServerConnection'](arg1);
}

export function RegisterServerService(arg1) {
  return window['go']['core']['App']['RegisterServerService'](arg1);
}

export function RemoveProjectFromLibrary(arg1, arg2) {
  return window['go']['core']['App']['RemoveProjectFromLibrary'](arg1, arg2);
}

export function RenameProject(arg1, arg2, arg3) {
  return window['go']['core']['App']['RenameProject'](arg1, arg2, arg3);
}

export function RequestExperimentIntegration(arg1, arg2) {
  return window['go']['core']['App']['RequestExperimentIntegration'](arg1, arg2);
}

export function ResizeProjectTerminal(arg1, arg2, arg3) {
  return window['go']['core']['App']['ResizeProjectTerminal'](arg1, arg2, arg3);
}

export function ResizeServerTerminal(arg1, arg2, arg3) {
  return window['go']['core']['App']['ResizeServerTerminal'](arg1, arg2, arg3);
}

export function ResolveAgentApproval(arg1, arg2) {
  return window['go']['core']['App']['ResolveAgentApproval'](arg1, arg2);
}

export function RestartApp(arg1) {
  return window['go']['core']['App']['RestartApp'](arg1);
}

export function RestartAppContext(arg1, arg2) {
  return window['go']['core']['App']['RestartAppContext'](arg1, arg2);
}

export function RestartServer(arg1) {
  return window['go']['core']['App']['RestartServer'](arg1);
}

export function RestoreExperiment(arg1, arg2) {
  return window['go']['core']['App']['RestoreExperiment'](arg1, arg2);
}

export function RunAppTests(arg1) {
  return window['go']['core']['App']['RunAppTests'](arg1);
}

export function RunAppTestsContext(arg1, arg2) {
  return window['go']['core']['App']['RunAppTestsContext'](arg1, arg2);
}

export function RunServerServiceHealthcheck(arg1, arg2, arg3) {
  return window['go']['core']['App']['RunServerServiceHealthcheck'](arg1, arg2, arg3);
}

export function SaveProjectWorkspace(arg1, arg2, arg3) {
  return window['go']['core']['App']['SaveProjectWorkspace'](arg1, arg2, arg3);
}

export function SaveProjectWorkspaceContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['SaveProjectWorkspaceContext'](arg1, arg2, arg3);
}

export function SelectProjectExperiment(arg1, arg2) {
  return window['go']['core']['App']['SelectProjectExperiment'](arg1, arg2);
}

export function SendAgentTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['core']['App']['SendAgentTask'](arg1, arg2, arg3, arg4, arg5);
}

export function SendAgentTaskContext(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['core']['App']['SendAgentTaskContext'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetAgentResourceSettings(arg1) {
  return window['go']['core']['App']['SetAgentResourceSettings'](arg1);
}

export function SetAppearance(arg1, arg2) {
  return window['go']['core']['App']['SetAppearance'](arg1, arg2);
}

export function SetArchived(arg1, arg2) {
  return window['go']['core']['App']['SetArchived'](arg1, arg2);
}

export function SetDefaultWSLDistribution(arg1) {
  return window['go']['core']['App']['SetDefaultWSLDistribution'](arg1);
}

export function SetEditorIntegrationEnabled(arg1, arg2) {
  return window['go']['core']['App']['SetEditorIntegrationEnabled'](arg1, arg2);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['core']['App']['SetFavorite'](arg1, arg2);
}

export function SetPreviewURL(arg1, arg2) {
  return window['go']['core']['App']['SetPreviewURL'](arg1, arg2);
}

export function SetPreviewURLContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['SetPreviewURLContext'](arg1, arg2, arg3);
}

export function SetPrimaryApp(arg1, arg2) {
  return window['go']['core']['App']['SetPrimaryApp'](arg1, arg2);
}

export function SetProjectGitHub(arg1, arg2, arg3) {
  return window['go']['core']['App']['SetProjectGitHub'](arg1, arg2, arg3);
}

export function SetProjectRoot(arg1) {
  return window['go']['core']['App']['SetProjectRoot'](arg1);
}

export function SmokeTestApp(arg1) {
  return window['go']['core']['App']['SmokeTestApp'](arg1);
}

export function StartApp(arg1) {
  return window['go']['core']['App']['StartApp'](arg1);
}

export function StartAppContext(arg1, arg2) {
  return window['go']['core']['App']['StartAppContext'](arg1, arg2);
}

export function StartMockServer(arg1) {
  return window['go']['core']['App']['StartMockServer'](arg1);
}

export function StartNativeEditor(arg1, arg2) {
  return window['go']['core']['App']['StartNativeEditor'](arg1, arg2);
}

export function StartProjectAgentTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['StartProjectAgentTerminal'](arg1, arg2, arg3, arg4);
}

export function StartProjectAgentTerminalContext(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['StartProjectAgentTerminalContext'](arg1, arg2, arg3, arg4);
}

export function StartProjectEditor(arg1, arg2) {
  return window['go']['core']['App']['StartProjectEditor'](arg1, arg2);
}

export function StartProjectEditorContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['StartProjectEditorContext'](arg1, arg2, arg3);
}

export function StartProjectTerminal(arg1, arg2, arg3) {
  return window['go']['core']['App']['StartProjectTerminal'](arg1, arg2, arg3);
}

export function StartProjectTerminalContext(arg1, arg2, arg3) {
  return window['go']['core']['App']['StartProjectTerminalContext'](arg1, arg2, arg3);
}

export function StartServer(arg1) {
  return window['go']['core']['App']['StartServer'](arg1);
}

export function StartServerTerminal(arg1) {
  return window['go']['core']['App']['StartServerTerminal'](arg1);
}

export function StopApp(arg1) {
  return window['go']['core']['App']['StopApp'](arg1);
}

export function StopAppContext(arg1, arg2) {
  return window['go']['core']['App']['StopAppContext'](arg1, arg2);
}

export function StopMockServer(arg1) {
  return window['go']['core']['App']['StopMockServer'](arg1);
}

export function StopProjectEditor(arg1) {
  return window['go']['core']['App']['StopProjectEditor'](arg1);
}

export function StopProjectTerminal(arg1) {
  return window['go']['core']['App']['StopProjectTerminal'](arg1);
}

export function StopServer(arg1) {
  return window['go']['core']['App']['StopServer'](arg1);
}

export function StopServerTerminal(arg1) {
  return window['go']['core']['App']['StopServerTerminal'](arg1);
}

export function TestAppRoute(arg1, arg2) {
  return window['go']['core']['App']['TestAppRoute'](arg1, arg2);
}

export function UngroupDuplicate(arg1) {
  return window['go']['core']['App']['UngroupDuplicate'](arg1);
}

export function UpdateApp(arg1, arg2) {
  return window['go']['core']['App']['UpdateApp'](arg1, arg2);
}

export function UpdateServerConnection(arg1) {
  return window['go']['core']['App']['UpdateServerConnection'](arg1);
}

export function UpdateServerService(arg1) {
  return window['go']['core']['App']['UpdateServerService'](arg1);
}

export function UpdateServicePosition(arg1, arg2, arg3, arg4) {
  return window['go']['core']['App']['UpdateServicePosition'](arg1, arg2, arg3, arg4);
}

export function VerifyServerConnection(arg1, arg2, arg3) {
  return window['go']['core']['App']['VerifyServerConnection'](arg1, arg2, arg3);
}

export function VerifyServerService(arg1, arg2, arg3) {
  return window['go']['core']['App']['VerifyServerService'](arg1, arg2, arg3);
}

export function WaitForAppHealthcheck(arg1, arg2) {
  return window['go']['core']['App']['WaitForAppHealthcheck'](arg1, arg2);
}

export function WriteProjectTerminal(arg1, arg2) {
  return window['go']['core']['App']['WriteProjectTerminal'](arg1, arg2);
}

export function WriteProjectTerminalBinary(arg1, arg2) {
  return window['go']['core']['App']['WriteProjectTerminalBinary'](arg1, arg2);
}

export function WriteServerTerminal(arg1, arg2) {
  return window['go']['core']['App']['WriteServerTerminal'](arg1, arg2);
}
