// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function AnalyzeExperimentChange(arg1:core.ExperimentChangeInput):Promise<core.ExperimentChangeAnalysis>;

export function ArchiveExperiment(arg1:string,arg2:boolean):Promise<core.Experiment>;

export function AttachRunningApp(arg1:core.AttachRunningAppInput):Promise<core.AppRuntimeStatus>;

export function BackupProject(arg1:string,arg2:string):Promise<string>;

export function CancelAgentTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CancelAgentTaskContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CancelClose():Promise<void>;

export function CancelImport():Promise<void>;

export function CaptureAppPreview(arg1:string):Promise<core.BrowserAutomationResult>;

export function CheckServerHealth(arg1:string):Promise<core.ServerHealth>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseProjectWorkspaceBackground(arg1:string,arg2:string):Promise<string>;

export function ChooseProjectWorkspaceFile(arg1:string,arg2:string):Promise<core.WorkspaceDocumentAsset>;

export function ChooseProjectWorkspacePhoto(arg1:string,arg2:string):Promise<core.WorkspacePhotoAsset>;

export function CleanupProjectRuntime(arg1:string):Promise<void>;

export function CleanupProjectServers(arg1:string):Promise<void>;

export function ClearProjectWorkspaceBackground(arg1:string,arg2:string):Promise<void>;

export function CloneRepository(arg1:string):Promise<core.Project>;

export function CompareExperiment(arg1:string):Promise<core.ExperimentComparison>;

export function ConfigureApp(arg1:string,arg2:core.AppInput):Promise<core.ProjectApp>;

export function ConfigureAppContext(arg1:string,arg2:string,arg3:core.AppInput):Promise<core.ProjectApp>;

export function ConfirmClose():Promise<void>;

export function ContinueExperimentChangeOnPrincipal(arg1:string,arg2:boolean):Promise<core.AgentApproval>;

export function ControlSpotifyPlayback(arg1:string):Promise<core.MediaPlaybackState>;

export function CreateApp(arg1:core.AppInput):Promise<core.ProjectApp>;

export function CreateExperiment(arg1:core.ExperimentCreateInput):Promise<core.Experiment>;

export function CreateExperimentCheckpoint(arg1:string):Promise<string>;

export function CreateProject(arg1:string):Promise<core.Project>;

export function CreateServerDraft(arg1:core.ServerInput):Promise<core.Server>;

export function DeleteApp(arg1:string):Promise<void>;

export function DeleteProject(arg1:string,arg2:string):Promise<void>;

export function DeleteProjectWorkspaceAsset(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProjectWorkspacePhoto(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DestroyServer(arg1:string):Promise<void>;

export function DetectDuplicateGroups(arg1:Array<core.ProjectCandidate>):Promise<Array<core.DuplicateGroup>>;

export function DetectTerminalApp(arg1:string):Promise<core.ManagedAppDetection>;

export function DiscardExperiment(arg1:core.ExperimentCleanupInput):Promise<core.Experiment>;

export function DiscoverApps(arg1:string):Promise<Array<core.AppCandidate>>;

export function EstimateImport(arg1:string):Promise<core.ImportEstimate>;

export function ExportProject(arg1:string,arg2:string):Promise<string>;

export function ExportServerReproducibleConfig(arg1:string,arg2:Array<string>,arg3:boolean):Promise<core.ServerReproducibleExport>;

export function FocusApp(arg1:string):Promise<void>;

export function GetAgentResourceSettings():Promise<core.AgentResourceSettings>;

export function GetAppConsoleErrors(arg1:string):Promise<core.BrowserAutomationResult>;

export function GetAppLogs(arg1:string):Promise<string>;

export function GetAppLogsContext(arg1:string,arg2:string):Promise<string>;

export function GetAppStatus(arg1:string):Promise<core.AppRuntimeStatus>;

export function GetAppStatusContext(arg1:string,arg2:string):Promise<core.AppRuntimeStatus>;

export function GetAppearance():Promise<core.Appearance>;

export function GetBrowserAutomationStatus(arg1:string):Promise<core.BrowserAutomationStatus>;

export function GetEditorIntegrations():Promise<Array<core.EditorIntegration>>;

export function GetProjectContext(arg1:string):Promise<core.ProjectContext>;

export function GetProjectRoot():Promise<string>;

export function GetProjectThumbnail(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspace(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspaceBackground(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspaceContext(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspacePhoto(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetServerLogs(arg1:string):Promise<string>;

export function GetServerStats(arg1:string):Promise<core.ServerStats>;

export function GetSpotifyPlayback():Promise<core.MediaPlaybackState>;

export function GetSpotifyPlaybackSince(arg1:string):Promise<core.MediaPlaybackState>;

export function GetWSLDistributions():Promise<Array<core.WSLDistributionResource>>;

export function GroupDuplicate(arg1:core.DuplicateGroup):Promise<void>;

export function ImportProjectWorkspaceAsset(arg1:string,arg2:string,arg3:string):Promise<core.WorkspaceDocumentAsset>;

export function ImportProjects(arg1:Array<string>):Promise<Array<core.Project>>;

export function Initialize():Promise<void>;

export function InstallEditorIntegration(arg1:string):Promise<Array<core.EditorIntegration>>;

export function InstallWSLDistribution(arg1:string):Promise<Array<core.WSLDistributionResource>>;

export function IntegrateExperiment(arg1:string,arg2:string,arg3:boolean):Promise<core.Experiment>;

export function LinkExperimentAgentSession(arg1:string,arg2:string):Promise<void>;

export function ListAllServers():Promise<Array<core.GlobalServer>>;

export function ListApps(arg1:string):Promise<Array<core.ProjectApp>>;

export function ListExperiments(arg1:string,arg2:string):Promise<Array<core.Experiment>>;

export function ListPendingAgentApprovals(arg1:string):Promise<Array<core.AgentApproval>>;

export function ListProjectAgentSessions(arg1:string,arg2:string):Promise<Array<core.AgentSession>>;

export function ListProjectAgentSessionsContext(arg1:string,arg2:string,arg3:string):Promise<Array<core.AgentSession>>;

export function ListProjectTerminalSessions(arg1:string,arg2:string):Promise<Array<core.ProjectTerminalSession>>;

export function ListProjectTerminalSessionsContext(arg1:string,arg2:string,arg3:string):Promise<Array<core.ProjectTerminalSession>>;

export function ListProjects(arg1:string,arg2:string):Promise<Array<core.Project>>;

export function ListServerConnections(arg1:string,arg2:string):Promise<Array<core.ServerConnection>>;

export function ListServerServices(arg1:string,arg2:string):Promise<Array<core.ServerService>>;

export function ListServers(arg1:string):Promise<Array<core.Server>>;

export function ListServersContext(arg1:string,arg2:string):Promise<Array<core.Server>>;

export function MoveNativeEditor(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function OpenProject(arg1:string):Promise<void>;

export function OpenProjectInEditor(arg1:string,arg2:string):Promise<void>;

export function PrepareExperimentIntegration(arg1:string,arg2:boolean):Promise<core.ExperimentReview>;

export function PrepareRuntimeClose():Promise<void>;

export function PrepareServerClose():Promise<void>;

export function RegisterServerConnection(arg1:core.ServerConnectionInput):Promise<core.ServerConnection>;

export function RegisterServerService(arg1:core.ServerServiceInput):Promise<core.ServerService>;

export function RemoveProjectFromLibrary(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string,arg3:string):Promise<core.Project>;

export function RequestExperimentIntegration(arg1:string,arg2:boolean):Promise<core.AgentApproval>;

export function ResizeProjectTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeServerTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveAgentApproval(arg1:string,arg2:boolean):Promise<core.AgentApproval>;

export function RestartApp(arg1:string):Promise<core.ProjectApp>;

export function RestartAppContext(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function RestartServer(arg1:string):Promise<core.Server>;

export function RestoreExperiment(arg1:string,arg2:boolean):Promise<core.Experiment>;

export function RunAppTests(arg1:string):Promise<core.ProjectApp>;

export function RunAppTestsContext(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function RunServerServiceHealthcheck(arg1:string,arg2:string,arg3:string):Promise<core.TopologyHealthcheckResult>;

export function SaveProjectWorkspace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveProjectWorkspaceContext(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectProjectExperiment(arg1:string,arg2:string):Promise<core.ProjectContext>;

export function SendAgentTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SendAgentTaskContext(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function SetAgentResourceSettings(arg1:core.AgentResourceSettings):Promise<core.AgentResourceSettings>;

export function SetAppearance(arg1:string,arg2:string):Promise<core.Appearance>;

export function SetArchived(arg1:string,arg2:boolean):Promise<core.Project>;

export function SetDefaultWSLDistribution(arg1:string):Promise<Array<core.WSLDistributionResource>>;

export function SetEditorIntegrationEnabled(arg1:string,arg2:boolean):Promise<Array<core.EditorIntegration>>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<core.Project>;

export function SetPreviewURL(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function SetPreviewURLContext(arg1:string,arg2:string,arg3:string):Promise<core.ProjectApp>;

export function SetPrimaryApp(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function SetProjectGitHub(arg1:string,arg2:string,arg3:string):Promise<core.Project>;

export function SetProjectRoot(arg1:string):Promise<string>;

export function SetProjectThumbnail(arg1:string,arg2:string):Promise<void>;

export function SmokeTestApp(arg1:string):Promise<core.BrowserAutomationResult>;

export function StartApp(arg1:string):Promise<core.ProjectApp>;

export function StartAppContext(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function StartDictation():Promise<void>;

export function StartMockServer(arg1:string):Promise<core.Server>;

export function StartNativeEditor(arg1:string,arg2:string):Promise<core.EditorSession>;

export function StartProjectAgentTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartProjectAgentTerminalContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartProjectEditor(arg1:string,arg2:string):Promise<core.EditorSession>;

export function StartProjectEditorContext(arg1:string,arg2:string,arg3:string):Promise<core.EditorSession>;

export function StartProjectTerminal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartProjectTerminalContext(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartProjectTerminalInFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartServer(arg1:string):Promise<core.Server>;

export function StartServerTerminal(arg1:string):Promise<string>;

export function StopApp(arg1:string):Promise<core.ProjectApp>;

export function StopAppContext(arg1:string,arg2:string):Promise<core.ProjectApp>;

export function StopMockServer(arg1:string):Promise<core.Server>;

export function StopProjectEditor(arg1:string):Promise<void>;

export function StopProjectTerminal(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<core.Server>;

export function StopServerTerminal(arg1:string):Promise<void>;

export function TestAppRoute(arg1:string,arg2:string):Promise<core.BrowserAutomationResult>;

export function UngroupDuplicate(arg1:string):Promise<void>;

export function UpdateApp(arg1:string,arg2:core.AppInput):Promise<core.ProjectApp>;

export function UpdateServerConnection(arg1:core.ServerConnectionInput):Promise<core.ServerConnection>;

export function UpdateServerService(arg1:core.ServerServiceInput):Promise<core.ServerService>;

export function UpdateServicePosition(arg1:string,arg2:string,arg3:string,arg4:string):Promise<core.ServerService>;

export function VerifyServerConnection(arg1:string,arg2:string,arg3:string):Promise<core.ServerConnection>;

export function VerifyServerService(arg1:string,arg2:string,arg3:string):Promise<core.ServerService>;

export function WaitForAppHealthcheck(arg1:string,arg2:number):Promise<core.BrowserAutomationResult>;

export function WriteProjectTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteProjectTerminalBinary(arg1:string,arg2:string):Promise<void>;

export function WriteServerTerminal(arg1:string,arg2:string):Promise<void>;
