// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeExperimentChange(arg1:main.ExperimentChangeInput):Promise<main.ExperimentChangeAnalysis>;

export function ArchiveExperiment(arg1:string,arg2:boolean):Promise<main.Experiment>;

export function AttachRunningApp(arg1:main.AttachRunningAppInput):Promise<main.AppRuntimeStatus>;

export function BackupProject(arg1:string,arg2:string):Promise<string>;

export function CancelAgentTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CancelAgentTaskContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CancelClose():Promise<void>;

export function CaptureAppPreview(arg1:string):Promise<main.BrowserAutomationResult>;

export function CheckServerHealth(arg1:string):Promise<main.ServerHealth>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function ChooseProjectWorkspaceBackground(arg1:string,arg2:string):Promise<string>;

export function ChooseProjectWorkspacePhoto(arg1:string,arg2:string):Promise<main.WorkspacePhotoAsset>;

export function CleanupProjectRuntime(arg1:string):Promise<void>;

export function CleanupProjectServers(arg1:string):Promise<void>;

export function ClearProjectWorkspaceBackground(arg1:string,arg2:string):Promise<void>;

export function CloneRepository(arg1:string):Promise<main.Project>;

export function CompareExperiment(arg1:string):Promise<main.ExperimentComparison>;

export function ConfigureApp(arg1:string,arg2:main.AppInput):Promise<main.ProjectApp>;

export function ConfigureAppContext(arg1:string,arg2:string,arg3:main.AppInput):Promise<main.ProjectApp>;

export function ConfirmClose():Promise<void>;

export function ContinueExperimentChangeOnPrincipal(arg1:string,arg2:boolean):Promise<main.AgentApproval>;

export function ControlSpotifyPlayback(arg1:string):Promise<main.MediaPlaybackState>;

export function CreateApp(arg1:main.AppInput):Promise<main.ProjectApp>;

export function CreateExperiment(arg1:main.ExperimentCreateInput):Promise<main.Experiment>;

export function CreateExperimentCheckpoint(arg1:string):Promise<string>;

export function CreateProject(arg1:string):Promise<main.Project>;

export function CreateServerDraft(arg1:main.ServerInput):Promise<main.Server>;

export function DeleteApp(arg1:string):Promise<void>;

export function DeleteProject(arg1:string,arg2:string):Promise<void>;

export function DeleteProjectWorkspacePhoto(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DestroyServer(arg1:string):Promise<void>;

export function DetectDuplicateGroups(arg1:Array<main.ProjectCandidate>):Promise<Array<main.DuplicateGroup>>;

export function DetectTerminalApp(arg1:string):Promise<main.ManagedAppDetection>;

export function DiscardExperiment(arg1:main.ExperimentCleanupInput):Promise<main.Experiment>;

export function DiscoverApps(arg1:string):Promise<Array<main.AppCandidate>>;

export function ExportProject(arg1:string,arg2:string):Promise<string>;

export function ExportServerReproducibleConfig(arg1:string,arg2:Array<string>,arg3:boolean):Promise<main.ServerReproducibleExport>;

export function FocusApp(arg1:string):Promise<void>;

export function GetAgentResourceSettings():Promise<main.AgentResourceSettings>;

export function GetAppConsoleErrors(arg1:string):Promise<main.BrowserAutomationResult>;

export function GetAppLogs(arg1:string):Promise<string>;

export function GetAppLogsContext(arg1:string,arg2:string):Promise<string>;

export function GetAppStatus(arg1:string):Promise<main.AppRuntimeStatus>;

export function GetAppStatusContext(arg1:string,arg2:string):Promise<main.AppRuntimeStatus>;

export function GetAppearance():Promise<main.Appearance>;

export function GetBrowserAutomationStatus(arg1:string):Promise<main.BrowserAutomationStatus>;

export function GetEditorIntegrations():Promise<Array<main.EditorIntegration>>;

export function GetProjectContext(arg1:string):Promise<main.ProjectContext>;

export function GetProjectRoot():Promise<string>;

export function GetProjectThumbnail(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspace(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspaceBackground(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspaceContext(arg1:string,arg2:string):Promise<string>;

export function GetProjectWorkspacePhoto(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetServerLogs(arg1:string):Promise<string>;

export function GetServerStats(arg1:string):Promise<main.ServerStats>;

export function GetSpotifyPlayback():Promise<main.MediaPlaybackState>;

export function GetSpotifyPlaybackSince(arg1:string):Promise<main.MediaPlaybackState>;

export function GetWSLDistributions():Promise<Array<main.WSLDistributionResource>>;

export function GroupDuplicate(arg1:main.DuplicateGroup):Promise<void>;

export function ImportProjects(arg1:Array<string>):Promise<Array<main.Project>>;

export function Initialize():Promise<void>;

export function InstallEditorIntegration(arg1:string):Promise<Array<main.EditorIntegration>>;

export function InstallWSLDistribution(arg1:string):Promise<Array<main.WSLDistributionResource>>;

export function IntegrateExperiment(arg1:string,arg2:string,arg3:boolean):Promise<main.Experiment>;

export function LinkExperimentAgentSession(arg1:string,arg2:string):Promise<void>;

export function ListAllServers():Promise<Array<main.GlobalServer>>;

export function ListApps(arg1:string):Promise<Array<main.ProjectApp>>;

export function ListExperiments(arg1:string,arg2:string):Promise<Array<main.Experiment>>;

export function ListPendingAgentApprovals(arg1:string):Promise<Array<main.AgentApproval>>;

export function ListProjectAgentSessions(arg1:string,arg2:string):Promise<Array<main.AgentSession>>;

export function ListProjectAgentSessionsContext(arg1:string,arg2:string,arg3:string):Promise<Array<main.AgentSession>>;

export function ListProjectTerminalSessions(arg1:string,arg2:string):Promise<Array<main.ProjectTerminalSession>>;

export function ListProjectTerminalSessionsContext(arg1:string,arg2:string,arg3:string):Promise<Array<main.ProjectTerminalSession>>;

export function ListProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function ListServerConnections(arg1:string,arg2:string):Promise<Array<main.ServerConnection>>;

export function ListServerServices(arg1:string,arg2:string):Promise<Array<main.ServerService>>;

export function ListServers(arg1:string):Promise<Array<main.Server>>;

export function ListServersContext(arg1:string,arg2:string):Promise<Array<main.Server>>;

export function MoveNativeEditor(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function OpenProject(arg1:string):Promise<void>;

export function OpenProjectInEditor(arg1:string,arg2:string):Promise<void>;

export function PrepareExperimentIntegration(arg1:string,arg2:boolean):Promise<main.ExperimentReview>;

export function PrepareRuntimeClose():Promise<void>;

export function PrepareServerClose():Promise<void>;

export function RegisterServerConnection(arg1:main.ServerConnectionInput):Promise<main.ServerConnection>;

export function RegisterServerService(arg1:main.ServerServiceInput):Promise<main.ServerService>;

export function RemoveProjectFromLibrary(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function RequestExperimentIntegration(arg1:string,arg2:boolean):Promise<main.AgentApproval>;

export function ResizeProjectTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeServerTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveAgentApproval(arg1:string,arg2:boolean):Promise<main.AgentApproval>;

export function RestartApp(arg1:string):Promise<main.ProjectApp>;

export function RestartAppContext(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function RestartServer(arg1:string):Promise<main.Server>;

export function RestoreExperiment(arg1:string,arg2:boolean):Promise<main.Experiment>;

export function RunAppTests(arg1:string):Promise<main.ProjectApp>;

export function RunAppTestsContext(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function RunServerServiceHealthcheck(arg1:string,arg2:string,arg3:string):Promise<main.TopologyHealthcheckResult>;

export function SaveProjectWorkspace(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveProjectWorkspaceContext(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectProjectExperiment(arg1:string,arg2:string):Promise<main.ProjectContext>;

export function SendAgentTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SendAgentTaskContext(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function SetAgentResourceSettings(arg1:main.AgentResourceSettings):Promise<main.AgentResourceSettings>;

export function SetAppearance(arg1:string,arg2:string):Promise<main.Appearance>;

export function SetArchived(arg1:string,arg2:boolean):Promise<main.Project>;

export function SetDefaultWSLDistribution(arg1:string):Promise<Array<main.WSLDistributionResource>>;

export function SetEditorIntegrationEnabled(arg1:string,arg2:boolean):Promise<Array<main.EditorIntegration>>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<main.Project>;

export function SetPreviewURL(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function SetPreviewURLContext(arg1:string,arg2:string,arg3:string):Promise<main.ProjectApp>;

export function SetPrimaryApp(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function SetProjectGitHub(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function SetProjectRoot(arg1:string):Promise<string>;

export function SmokeTestApp(arg1:string):Promise<main.BrowserAutomationResult>;

export function StartApp(arg1:string):Promise<main.ProjectApp>;

export function StartAppContext(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function StartMockServer(arg1:string):Promise<main.Server>;

export function StartNativeEditor(arg1:string,arg2:string):Promise<main.EditorSession>;

export function StartProjectAgentTerminal(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartProjectAgentTerminalContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartProjectEditor(arg1:string,arg2:string):Promise<main.EditorSession>;

export function StartProjectEditorContext(arg1:string,arg2:string,arg3:string):Promise<main.EditorSession>;

export function StartProjectTerminal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartProjectTerminalContext(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartServer(arg1:string):Promise<main.Server>;

export function StartServerTerminal(arg1:string):Promise<string>;

export function StopApp(arg1:string):Promise<main.ProjectApp>;

export function StopAppContext(arg1:string,arg2:string):Promise<main.ProjectApp>;

export function StopMockServer(arg1:string):Promise<main.Server>;

export function StopProjectEditor(arg1:string):Promise<void>;

export function StopProjectTerminal(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<main.Server>;

export function StopServerTerminal(arg1:string):Promise<void>;

export function TestAppRoute(arg1:string,arg2:string):Promise<main.BrowserAutomationResult>;

export function UngroupDuplicate(arg1:string):Promise<void>;

export function UpdateApp(arg1:string,arg2:main.AppInput):Promise<main.ProjectApp>;

export function UpdateServerConnection(arg1:main.ServerConnectionInput):Promise<main.ServerConnection>;

export function UpdateServerService(arg1:main.ServerServiceInput):Promise<main.ServerService>;

export function UpdateServicePosition(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ServerService>;

export function VerifyServerConnection(arg1:string,arg2:string,arg3:string):Promise<main.ServerConnection>;

export function VerifyServerService(arg1:string,arg2:string,arg3:string):Promise<main.ServerService>;

export function WaitForAppHealthcheck(arg1:string,arg2:number):Promise<main.BrowserAutomationResult>;

export function WriteProjectTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteProjectTerminalBinary(arg1:string,arg2:string):Promise<void>;

export function WriteServerTerminal(arg1:string,arg2:string):Promise<void>;
