// Funny rotating greetings for the Home chat bar. Pools per time of day plus
// day-of-week extras; a phrase never repeats until its whole pool was shown.

const madrugada = [
  "Hola noctámbulo, ¿quemando tokens a las 3am otra vez?",
  "Las mejores ideas nacen cuando el sol duerme. Dicen.",
  "¿Insomnio o inspiración? Acá no juzgamos.",
  "El deploy de madrugada es un deporte extremo.",
  "Todo el mundo duerme. Vos y yo, a lo nuestro.",
  "Los bugs también duermen. Aprovechá.",
  "Café frío, ideas calientes. Clásico de las 2am.",
  "¿Otra vez despierto? El código no se escribe solo... todavía.",
  "Modo búho activado. Ulula si necesitás algo.",
  "La madrugada: cuando el 'un commit más' se vuelve mentira.",
  "Sereno moreno. ¿Qué compilamos hoy?",
  "Si estás acá a esta hora, más vale que sea importante. O divertido.",
  "3am: la hora oficial de 'mejor lo reescribo todo'.",
  "Ni el gallo se levantó y vos ya estás tirando código.",
  "Bienvenido al club de los que ven amanecer por accidente.",
  "Tus ojeras dicen 'sprint', tu corazón dice 'refactor'.",
  "Shhh... los servidores están durmiendo. Mentira, dale.",
  "La luna es testigo de tus mejores commits.",
  "¿Sabías que dormir también arregla bugs? Solo digo.",
  "Madrugada productiva o espiral de videos. Elegí sabiamente.",
  "Hora ideal: cero notificaciones, cero excusas.",
  "El silencio de las 4am compila más rápido.",
  "Vampiro del código, bienvenido a tu oficina.",
  "Otro día que le ganamos al amanecer.",
  "Tu yo de mañana pagará esto. Tu yo de ahora, a darle.",
  "¿Cenaste o desayunaste? A esta hora ya nadie sabe.",
  "Los grandes imperios se fundaron a las 2am. Probablemente.",
  "Insomnio + ideas = peligro para producción.",
  "Nadie te ve, pero el historial de commits sí.",
  "La madrugada no juzga tu música ni tu código.",
  "Trasnochar es gratis. El deploy roto, no.",
  "A estas horas hasta el linter tiene sueño.",
  "Punto de guardado: ¿y si dormís un toque?",
  "Las estrellas brillan, tu pantalla más.",
  "Hola criatura de la noche, ¿qué construimos?",
]

const manana = [
  "Buen día, ¿café primero o bugs primero?",
  "Arrancamos: el teclado no se calienta solo.",
  "Hoy es un gran día para romper producción. Digo, mejorar.",
  "Mañana fresca, ideas frescas, commits frescos.",
  "Buenos días. Los TODO de ayer dicen hola.",
  "El sol salió y tus pendientes también.",
  "Desayuno de campeones: café y un git pull.",
  "Nuevo día, nuevo 'funciona en mi máquina'.",
  "Madrugaste: los servidores están impresionados.",
  "Primera regla de la mañana: no tocar nada antes del café.",
  "Hoy sí terminamos eso. Hoy sí.",
  "Buenos días, humano funcional. A producir.",
  "El pájaro madrugador atrapa... el mejor merge.",
  "Energía matutina: úsala antes de que llegue la primera reunión.",
  "Un buen día empieza con inbox cero. Jaja, chiste.",
  "Café cargado, ideas claras, bugs temblando.",
  "La mañana es tuya. La tarde ya veremos.",
  "Hola, ¿dormiste o solo parpadeaste largo?",
  "Que tu café sea fuerte y tu WiFi estable.",
  "Sol afuera, focus adentro.",
  "Los mejores deploys se hacen antes del mediodía. Dicen los valientes.",
  "Día nuevo, backlog viejo. Vamos.",
  "Tu agenda dice reuniones, tu corazón dice codear.",
  "Buenos días. Recordá: hidratarse también es productividad.",
  "El código de la mañana huele a victoria.",
  "Arranquemos antes de que el día tenga otras ideas.",
  "Hoy el plan es simple: hacer que funcione.",
  "Madrugar tiene premio: nadie te escribe todavía.",
  "Primera misión del día: no romper nada antes de las 10.",
  "Se abre una nueva partida. Elegí tu misión.",
  "Buenos días, estratega. ¿Qué conquistamos hoy?",
  "Café en mano, mundo a los pies.",
  "Que el standup sea corto y el enfoque largo.",
  "Hoy es viernes en tu corazón, aunque sea martes.",
  "Modo mañana: optimismo al 100%, batería al 100%.",
  "El futuro se escribe por la mañana. O al menos se planea.",
  "Buen día. El bug de ayer amaneció más débil.",
  "Sonreí: todavía no llegó ningún ticket urgente.",
  "La productividad matutina es real. Aprovechala antes que expire.",
  "Un commit por la mañana mantiene al caos en calma.",
  "Buenos días. Hoy toca brillar (y compilar).",
  "Levantarse temprano: el primer refactor del día.",
  "Mañana despejada, consola limpia.",
  "Hola sol, hola pendientes, hola vos.",
  "Empezá suave: un té, un scroll, un git status.",
]

const tarde = [
  "Buenas tardes, ¿cómo va esa batalla contra el backlog?",
  "La siesta es tentadora, el deploy es urgente. Dilema.",
  "Mediodía: hora de fingir que el almuerzo fue liviano.",
  "La tarde es joven y los bugs no se matan solos.",
  "¿Café de las 3 o energía pura? Mentí si querés.",
  "Sobremesa productiva: lo mejor de dos mundos.",
  "A esta hora el cerebro pide memes, dale código.",
  "Tarde de foco: silenciá el grupo, abrí la terminal.",
  "El sol pega fuerte, tu código más.",
  "Mitad del día, mitad del backlog. Matemática perfecta.",
  "Buenas tardes. El bug de la mañana sigue esperando.",
  "Post-almuerzo: donde las promesas de productividad van a descansar.",
  "Quedan horas útiles. Úsalas antes de que se conviertan en series.",
  "La tarde ideal: música, código y cero reuniones.",
  "¿Ya merendaste? Los grandes refactors piden azúcar.",
  "Hora pico de ideas. O de sueño. Vos decidís.",
  "El deploy de la tarde: valiente pero razonable.",
  "Tarde soleada, terminal abierta. Equilibrio.",
  "Las 4pm: cuando el café deja de ser opcional.",
  "Todavía hay tiempo de salvar el día. Dale.",
  "Buenas tardes, máquina. ¿Seguimos donde quedamos?",
  "El segundo aire llega justo... ahora.",
  "Entre el almuerzo y la cena está la gloria.",
  "Tarde de martes con energía de viernes. Se respeta.",
  "Un push a esta hora y te vas tranquilo.",
  "La tarde no perdona: o producís o scrolleás.",
  "Quedan pocas horas de luz, muchas de inspiración.",
  "¿Reunión que pudo ser un mail? Recuperá el tiempo acá.",
  "Modo tarde: pragmatismo puro.",
  "Cerrá pestañas, abrí posibilidades.",
  "La tarde es para terminar, no para empezar de cero. (Guiño.)",
  "Tu to-do list te mira fijo desde las 2pm.",
  "Café, agua o fuerza de voluntad. Elegí tu combustible.",
  "El sol baja, tu productividad sube. Así funciona, ¿no?",
  "Buenas tardes. Producción sigue viva, celebremos.",
  "Es esa hora rara: ni almuerzo ni salida. Perfecta para codear.",
  "Un buen commit a las 5 vale por dos de las 11.",
  "La tarde avanza y el bug retrocede. Seguí así.",
  "Momento ideal para ese refactor que venís posponiendo.",
  "Últimas horas hábiles: modo francotirador.",
  "¿Y si cerramos un ticket antes de la cena?",
  "La tarde te da una segunda oportunidad. Tomala.",
  "Menos pestañas, más resultados.",
  "Ya casi. Un empujón más y el día queda en verde.",
  "Buenas tardes, crack. El teclado te extrañaba.",
]

const noche = [
  "Buenas noches, ¿un último commit antes de dormir?",
  "La noche es joven y el código también.",
  "Cena liviana, deploy pesado. Balance.",
  "Hora de programar con música triste y resultados felices.",
  "El 'ya casi termino' nocturno: un clásico.",
  "Noche de código: donde el tiempo vuela y los bugs también.",
  "¿Serie o terminal? Tu historial dice terminal.",
  "Las mejores ideas llegan justo cuando ibas a cerrar la laptop.",
  "Buenas noches. El sol se fue, el foco llegó.",
  "Un push nocturno y a la cama como un campeón.",
  "La noche no cuenta calorías ni líneas de código.",
  "Modo nocturno activado. En la app y en la vida.",
  "Últimas horas del día: perfectas para lo importante.",
  "¿Trabajando de noche o viviendo de noche? Ambas valen.",
  "El código nocturno tiene otro sabor. Más épico.",
  "Cerrando el día: ¿qué dejamos listo para mañana?",
  "La luna aprueba tu dedicación. Tu almohada, no tanto.",
  "Noche tranquila, commits limpios.",
  "Nadie molesta a esta hora. Momento de oro.",
  "Un bug menos y te ganás el postre.",
  "La cena puede esperar, esta idea no.",
  "Empezó la función nocturna. Vos sos el protagonista.",
  "Hoy rendiste. Esto de ahora es bonus track.",
  "Cierre del día: guardá, commiteá, respirá.",
  "¿El último esfuerzo del día o el primero de la noche?",
  "Noches así construyen proyectos así.",
  "Tu pijama y tu IDE: la dupla perfecta.",
  "Silencio afuera, ruido de teclas adentro.",
  "El día termina, el side project despierta.",
  "Buenas noches. Que el deploy te acompañe.",
  "Última misión del día: nada de producción sin backup.",
  "Hora de código con manta. Confort nivel dios.",
  "La noche premia a los constantes.",
  "¿Un capítulo más o un feature más? Conozco tu respuesta.",
  "Todo gran lanzamiento empezó una noche cualquiera.",
  "Cerrá el día con un git push y la conciencia limpia.",
  "Noche estrellada, consola despejada.",
  "El cansancio es temporal, el commit es para siempre.",
  "Si el código funciona a la primera, andá a dormir. Es una señal.",
  "Las 10pm: hora oficial de 'lo termino y me acuesto'.",
  "Buenas noches, arquitecto de madrugadas.",
  "Un té, un lo-fi, un bug. La santísima trinidad.",
  "Mañana es otro día, pero esta idea es de hoy.",
  "El descanso también compila. No lo olvides.",
  "Que sueñes con merges sin conflictos.",
]

const lunes = [
  "Lunes: el jefe final de la semana. Vos podés.",
  "Arrancó el lunes. El café ya lo sabe.",
  "Lunes de reset: semana nueva, bugs nuevos.",
  "Nadie ama los lunes, pero los lunes traen deploys.",
  "Lunes: día oficial de 'la semana que viene empiezo'... es hoy.",
  "Semana nueva, sprint nuevo, vos renovado. Más o menos.",
  "El lunes se vence con un buen primer commit.",
  "Lunes por la mañana: modo diésel, arranca lento pero arranca.",
  "Hoy es lunes. Respirá hondo y abrí la terminal.",
  "Lunes: donde los planes del viernes vienen a rendir cuentas.",
  "Que este lunes te encuentre compilando.",
  "Lunes con actitud de jueves. Se puede.",
  "Primer día de la semana: plantá la bandera temprano.",
  "El lunes no es tu enemigo. El scope creep sí.",
  "Lunes: cargando motivación... 87%.",
]

const viernes = [
  "¡Viernes! El deploy de hoy es bajo tu propio riesgo.",
  "Viernes: día de commits valientes y arrepentimientos el lunes.",
  "Regla de oro: viernes sin deploy, finde sin sustos.",
  "Viernes, mi amigo. Cerremos la semana con estilo.",
  "Último esfuerzo: el finde está ahí nomás.",
  "Viernes de código ligero y espíritu liviano.",
  "Hoy todo el mundo trabaja en modo avión. Vos disimulá.",
  "Viernes: el sprint agoniza, vos florecés.",
  "Un push más y a disfrutar el finde.",
  "Viernes por la tarde: la hora más peligrosa para tocar producción.",
  "Cerrá tickets, no abras incendios. Es viernes.",
  "El viernes premia a los que documentaron el miércoles.",
  "Viernes: guardá todo dos veces, por las dudas.",
  "Se siente el finde en el aire. Y en el CPU.",
  "Feliz viernes: que tu build esté verde y tu agenda vacía.",
]

const finde = [
  "¿Trabajando en finde? Eso es amor al arte. O un deadline.",
  "Sábado de código: los héroes no descansan.",
  "El finde es tuyo: proyecto propio, reglas propias.",
  "Fin de semana: cero reuniones, máxima creatividad.",
  "Domingo de ideas locas. Las mejores nacen así.",
  "Weekend mode: código sin corbata.",
  "¿Finde productivo o finde de sofá? Podés tener ambos.",
  "Hoy no hay standup. Disfrutalo codeando a tu ritmo.",
  "Los side projects viven de findes como este.",
  "Sábado: el día perfecto para romper cosas sin culpa.",
  "Domingo a la tarde: donde nacen los planes de la semana.",
  "Finde + café + código = terapia.",
  "Nadie te apura hoy. Ni el CI.",
  "El finde es para experimentar. Producción ni la mires.",
  "Código de fin de semana: puro placer, cero tickets.",
  "Hoy programás porque querés, no porque debés. Se nota.",
  "Fin de semana: modo laboratorio activado.",
  "Que este finde tu única alarma sea el horno.",
  "Domingo: día de descanso... y de 'una ideíta nomás'.",
  "El lunes queda lejos. Aprovechá la paz.",
]

const nightOwlEn = [
  "Hey night owl, burning tokens at 3am again?",
  "The best ideas show up when the sun's asleep. Allegedly.",
  "Insomnia or inspiration? No judgment here.",
  "A 3am deploy is an extreme sport.",
  "Everyone's asleep. You and me, let's get to it.",
  "Even the bugs are sleeping. Strike now.",
  "Cold coffee, hot ideas. A 2am classic.",
  "Awake again? Code doesn't write itself... yet.",
  "Owl mode on. Hoot if you need anything.",
  "Late night: where 'one more commit' becomes a lie.",
  "Well well, look who's still up. What are we compiling?",
  "If you're here at this hour, it better be important. Or fun.",
  "3am: the official hour of 'let's just rewrite everything'.",
  "The rooster isn't even up and you're already shipping.",
  "Welcome to the club of accidental sunrise watchers.",
  "Your dark circles say 'sprint', your heart says 'refactor'.",
  "Shhh... the servers are sleeping. Kidding, go ahead.",
  "The moon has witnessed your finest commits.",
  "Fun fact: sleep also fixes bugs. Just saying.",
  "Productive all-nighter or video spiral? Choose wisely.",
  "Prime time: zero notifications, zero excuses.",
  "The 4am silence compiles faster.",
  "Code vampire, welcome to your office.",
  "Another day we beat the sunrise.",
  "Tomorrow-you will pay for this. Tonight-you, let's go.",
  "Dinner or breakfast? At this hour nobody knows.",
  "Great empires were founded at 2am. Probably.",
  "Insomnia + ideas = danger for production.",
  "Nobody sees you, but the commit history does.",
  "The night judges neither your music nor your code.",
  "Staying up is free. A broken deploy is not.",
  "At this hour even the linter is sleepy.",
  "Checkpoint: what if you slept a little?",
  "The stars are bright. Your screen, brighter.",
  "Hello creature of the night, what are we building?",
]

const morningEn = [
  "Morning! Coffee first or bugs first?",
  "Let's go: the keyboard won't warm itself.",
  "Great day to break production. I mean, improve it.",
  "Fresh morning, fresh ideas, fresh commits.",
  "Good morning. Yesterday's TODOs say hi.",
  "The sun is up and so is your backlog.",
  "Breakfast of champions: coffee and a git pull.",
  "New day, new 'works on my machine'.",
  "Up early: the servers are impressed.",
  "Rule one of the morning: touch nothing before coffee.",
  "Today we finish that thing. Today for real.",
  "Good morning, functional human. Let's produce.",
  "The early bird catches... the cleanest merge.",
  "Morning energy: use it before the first meeting eats it.",
  "A good day starts with inbox zero. Haha, good one.",
  "Strong coffee, clear ideas, trembling bugs.",
  "The morning is yours. The afternoon, we'll see.",
  "Hey, did you sleep or just blink slowly?",
  "May your coffee be strong and your WiFi stable.",
  "Sun outside, focus inside.",
  "The best deploys happen before noon. Say the brave.",
  "New day, old backlog. Let's move.",
  "Your calendar says meetings, your heart says code.",
  "Good morning. Reminder: hydration is also productivity.",
  "Morning code smells like victory.",
  "Let's start before the day gets other ideas.",
  "Today's plan is simple: make it work.",
  "Early start bonus: nobody's texting you yet.",
  "First mission: break nothing before 10am.",
  "A new run begins. Pick your quest.",
  "Good morning, strategist. What do we conquer today?",
  "Coffee in hand, world at your feet.",
  "May the standup be short and the focus long.",
  "It's Friday in your heart, even if it's Tuesday.",
  "Morning mode: optimism 100%, battery 100%.",
  "The future is written in the morning. Or at least planned.",
  "Good morning. Yesterday's bug woke up weaker.",
  "Smile: no urgent tickets have arrived. Yet.",
  "Morning productivity is real. Use it before it expires.",
  "A commit in the morning keeps the chaos away.",
  "Good morning. Time to shine (and compile).",
  "Waking up early: the day's first refactor.",
  "Clear morning, clean console.",
  "Hello sun, hello backlog, hello you.",
  "Start gentle: a tea, a scroll, a git status.",
]

const afternoonEn = [
  "Good afternoon, how goes the battle against the backlog?",
  "The nap is tempting, the deploy is urgent. Dilemma.",
  "Noon: time to pretend lunch was light.",
  "The afternoon is young and bugs don't fix themselves.",
  "3pm coffee or pure willpower? You can lie.",
  "Post-lunch focus: the best of both worlds.",
  "Your brain wants memes. Feed it code.",
  "Focus time: mute the group chat, open the terminal.",
  "The sun hits hard. Your code hits harder.",
  "Half the day gone, half the backlog left. Perfect math.",
  "Good afternoon. This morning's bug is still waiting.",
  "Post-lunch: where productivity promises go to rest.",
  "Useful hours remain. Spend them before they become a series.",
  "The ideal afternoon: music, code, zero meetings.",
  "Snack time? Great refactors run on sugar.",
  "Peak hour for ideas. Or naps. Your call.",
  "The afternoon deploy: brave but reasonable.",
  "Sunny afternoon, open terminal. Balance.",
  "4pm: when coffee stops being optional.",
  "There's still time to save the day. Go.",
  "Good afternoon, machine. Shall we pick up where we left off?",
  "Second wind arriving in three, two, one...",
  "Between lunch and dinner lies glory.",
  "Tuesday afternoon with Friday energy. Respect.",
  "One push now and you leave in peace.",
  "The afternoon forgives nothing: produce or scroll.",
  "Few hours of daylight left, plenty of inspiration.",
  "That meeting could've been an email? Reclaim the time here.",
  "Afternoon mode: pure pragmatism.",
  "Close tabs, open possibilities.",
  "Afternoons are for finishing, not starting over. (Wink.)",
  "Your to-do list has been staring since 2pm.",
  "Coffee, water, or sheer willpower. Pick your fuel.",
  "Sun goes down, productivity goes up. That's how it works, right?",
  "Good afternoon. Production is still alive. Celebrate.",
  "That weird hour: not lunch, not quitting time. Perfect for code.",
  "A good commit at 5 is worth two at 11.",
  "The afternoon advances and the bug retreats. Keep going.",
  "Perfect moment for that refactor you keep postponing.",
  "Last working hours: sniper mode.",
  "What if we close one ticket before dinner?",
  "The afternoon gives you a second chance. Take it.",
  "Fewer tabs, more results.",
  "Almost there. One more push and the day turns green.",
  "Good afternoon, champ. The keyboard missed you.",
]

const eveningEn = [
  "Good evening, one last commit before bed?",
  "The night is young and so is the code.",
  "Light dinner, heavy deploy. Balance.",
  "Time to code with sad music and happy results.",
  "The nightly 'almost done': a timeless classic.",
  "Night coding: where time flies and so do bugs.",
  "Series or terminal? Your history says terminal.",
  "The best ideas arrive right as you close the laptop.",
  "Good evening. The sun left, the focus arrived.",
  "One night push and off to bed like a champion.",
  "The night counts neither calories nor lines of code.",
  "Dark mode: in the app and in life.",
  "The day's last hours: perfect for what matters.",
  "Working nights or living nights? Both count.",
  "Night code tastes different. More epic.",
  "Closing the day: what do we leave ready for tomorrow?",
  "The moon approves your dedication. Your pillow, less so.",
  "Quiet night, clean commits.",
  "Nobody bothers you now. Golden hour.",
  "One less bug and you've earned dessert.",
  "Dinner can wait. This idea can't.",
  "The night show has started. You're the lead.",
  "You did well today. This is bonus content.",
  "Day's end: save, commit, breathe.",
  "The day's last effort or the night's first?",
  "Nights like this build projects like yours.",
  "Pajamas and an IDE: the perfect duo.",
  "Silence outside, keystrokes inside.",
  "The day ends, the side project wakes up.",
  "Good evening. May the deploy be with you.",
  "Final quest of the day: no production without backup.",
  "Blanket coding hours. Peak comfort.",
  "The night rewards the consistent.",
  "One more episode or one more feature? I know your answer.",
  "Every great launch started on an ordinary night.",
  "Close the day with a git push and a clear conscience.",
  "Starry night, clear console.",
  "Fatigue is temporary. Commits are forever.",
  "If the code works on the first try, go to sleep. It's a sign.",
  "10pm: official hour of 'I'll finish this and go to bed'.",
  "Good evening, architect of late nights.",
  "A tea, some lo-fi, one bug. The holy trinity.",
  "Tomorrow is another day, but this idea is today's.",
  "Rest also compiles. Don't forget it.",
  "May you dream of merges without conflicts.",
]

const mondayEn = [
  "Monday: the week's final boss. You've got this.",
  "Monday has begun. The coffee already knows.",
  "Monday reset: new week, new bugs.",
  "Nobody loves Mondays, but Mondays bring deploys.",
  "Monday: official day of 'I'll start next week'... it's now.",
  "New week, new sprint, renewed you. More or less.",
  "Mondays are defeated with a good first commit.",
  "Monday morning: diesel mode. Slow start, but it starts.",
  "It's Monday. Deep breath, open the terminal.",
  "Monday: where Friday's plans come to be judged.",
  "May this Monday find you compiling.",
  "Monday with Thursday attitude. It can be done.",
  "First day of the week: plant your flag early.",
  "Monday isn't your enemy. Scope creep is.",
  "Monday: loading motivation... 87%.",
]

const fridayEn = [
  "Friday! Today's deploy is at your own risk.",
  "Friday: day of brave commits and Monday regrets.",
  "Golden rule: no Friday deploys, no weekend scares.",
  "Friday, my friend. Let's close the week in style.",
  "One last push: the weekend is right there.",
  "Friday: light code, lighter spirit.",
  "Everyone's in airplane mode today. Act natural.",
  "Friday: the sprint fades, you flourish.",
  "One more push and the weekend is yours.",
  "Friday afternoon: the most dangerous hour to touch production.",
  "Close tickets, don't open fires. It's Friday.",
  "Friday rewards those who documented on Wednesday.",
  "Friday: save everything twice, just in case.",
  "You can feel the weekend in the air. And in the CPU.",
  "Happy Friday: green builds and an empty calendar.",
]

const weekendEn = [
  "Working on a weekend? That's love of the craft. Or a deadline.",
  "Saturday code: heroes don't rest.",
  "The weekend is yours: your project, your rules.",
  "Weekend: zero meetings, maximum creativity.",
  "Sunday of wild ideas. The best ones start here.",
  "Weekend mode: code without a tie.",
  "Productive weekend or couch weekend? Why not both.",
  "No standup today. Enjoy coding at your own pace.",
  "Side projects live off weekends like this one.",
  "Saturday: the perfect day to break things guilt-free.",
  "Sunday afternoon: where next week's plans are born.",
  "Weekend + coffee + code = therapy.",
  "Nobody's rushing you today. Not even the CI.",
  "Weekends are for experiments. Don't even look at production.",
  "Weekend code: pure joy, zero tickets.",
  "Today you code because you want to. It shows.",
  "Weekend: laboratory mode engaged.",
  "May your only alarm this weekend be the oven.",
  "Sunday: day of rest... and of 'just one tiny idea'.",
  "Monday is far away. Enjoy the peace.",
]

export type GreetingLang = "es" | "en"

export function isGreetingLang(value: unknown): value is GreetingLang {
  return value === "es" || value === "en"
}

const pools = {
  es: { night: madrugada, morning: manana, afternoon: tarde, evening: noche, monday: lunes, friday: viernes, weekend: finde },
  en: { night: nightOwlEn, morning: morningEn, afternoon: afternoonEn, evening: eveningEn, monday: mondayEn, friday: fridayEn, weekend: weekendEn },
} as const

const usedKey = "seizen-greetings-used"

export function nextGreeting(lang: GreetingLang = "es", now = new Date()): string {
  const hour = now.getHours()
  const day = now.getDay()
  const slots = pools[lang]
  let pool: readonly string[] =
    hour < 6 ? slots.night : hour < 12 ? slots.morning : hour < 19 ? slots.afternoon : slots.evening
  if (day === 1) pool = pool.concat(slots.monday)
  else if (day === 5) pool = pool.concat(slots.friday)
  else if (day === 0 || day === 6) pool = pool.concat(slots.weekend)

  let used: string[] = []
  try {
    const parsed: unknown = JSON.parse(localStorage.getItem(usedKey) ?? "[]")
    if (Array.isArray(parsed)) used = parsed.filter((p) => typeof p === "string")
  } catch {
    // Corrupt storage just means every phrase is fresh again.
  }

  let fresh: readonly string[] = pool.filter((phrase) => !used.includes(phrase))
  if (fresh.length === 0) {
    // This pool got exhausted; forget only its phrases and start it over.
    used = used.filter((phrase) => !pool.includes(phrase))
    fresh = pool
  }

  const pick = fresh[Math.floor(Math.random() * fresh.length)]
  localStorage.setItem(usedKey, JSON.stringify([...used, pick]))
  return pick
}
